---

- hosts: all
  gather_facts: no
  connection: local
  
  vars:
    creds:
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:
  - name: Change local enable secret
    ios_config:
      lines:
        - enable secret SuPeRsEcReT  #Enter the enable password here
      replace: line

  - name: Change Password for local user
    ios_user:
      name: local_dude
      configured_password: CrAzYsEcReT #Enter the new local_dude password here
      update_password: always
      privilege: 15
      state: present
